const REPLACE_COLLECTION_SUCCESSFUL = 'REPLACE COLLECTION SUCCESSFUL';
const CREATE_ENTRY_SUCCESSFUL = 'CREATE ENTRY SUCCESSFUL';
const DELETE_COLLECTION_SUCCESSFUL = 'DELETE COLLECTION SUCCESSFUL';
const UPDATE_ITEM_SUCCESSFUL = 'UPDATE ITEM SUCCESSFUL';
const DELETE_ITEM_SUCCESSFUL = 'DELETE ITEM SUCCESSFUL';
const ALL_TESTS_SUCCESSFUL = 'ALL TESTS SUCCESSFUL';


module.exports = {
    REPLACE_COLLECTION_SUCCESSFUL,
    CREATE_ENTRY_SUCCESSFUL,
    DELETE_COLLECTION_SUCCESSFUL,
    UPDATE_ITEM_SUCCESSFUL,
    DELETE_ITEM_SUCCESSFUL,
    ALL_TESTS_SUCCESSFUL
}